version: '3.8'
services:
  db:
    image: postgres:13
    container_name: timerecording_db
    environment:
      POSTGRES_USER: timerecording_user
      POSTGRES_PASSWORD: secure_password123
      POSTGRES_DB: timerecording
    ports:
      - "5432:5432" # Port am Host : Port im Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: pdunkel/kernalpanic-timerecording:latest # Name des lokalen Images
    container_name: kernelpanic-timerecording_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Ãœberschreibt Einstellungen in application.properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/timerecording
      SPRING_DATASOURCE_USERNAME: timerecording_user
      SPRING_DATASOURCE_PASSWORD: secure_password123


volumes:
  postgres_data: